/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void gtl__init(void);
static void gtl__update60(void);
static void gtl__draw(void);

int gtl_playing = 1;
int gtl_flash = 0;

static void gtl__init(void)
{
    gt_music(0, 1);
}

static void gtl__update60(void)
{
    if (((gt_rpt0 & 16u) != 0)) {
        gt_sfx(0, -1);
        gtl_flash = 8;
    }
    if (((gt_rpt0 & 4096u) != 0)) {
        gt_sfx(3, -1);
        gtl_flash = 8;
    }
    if (((gt_rpt0 & 8192u) != 0)) {
        gt_sfx(1, -1);
        gtl_flash = 8;
    }
    if (((gt_rpt0 & 1028u) != 0)) {
        gt_sfx(5, 2);
        gtl_flash = 8;
    }
    if (((gt_rpt0 & 2056u) != 0)) {
        if ((gtl_playing == 1)) {
            gt_music((-1), 1);
            gtl_playing = 0;
        } else {
            gt_music(0, 1);
            gtl_playing = 1;
        }
    }
    if ((gtl_flash > 0)) {
        gtl_flash = (gtl_flash - 1);
    }
}

static void gtl__draw(void)
{
    gt_p8_cls(169);
    { int gtl_c = 8;
        if ((gtl_flash > 0)) {
            gtl_c = 10;
        }
        (gt_a0 = 64, gt_a1 = 60, gt_a2 = 20, gt_a3 = gtl_c, gt_p8_circfill_z());
        gt_p8_print("sfx + music", 34, 18, 7);
        if ((gtl_playing == 1)) {
            gt_p8_print("music: on", 42, 100, 254);
        } else {
            gt_p8_print("music: off", 40, 100, 91);
        }
    }
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    gt_audio_init();
    gt_music_init();
    gtl__init();
    for (;;) {
        gt_update_inputs();
        gtl__update60();
        gtl__draw();
        gt_endframe();
    }
}
