/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__init(void);
static void lcl__update60(void);
static void lcl__draw(void);

int lcl_playing = 1;
int lcl_flash = 0;

static void lcl__init(void)
{
    gt_music(0, 1);
}

static void lcl__update60(void)
{
    if (((gt_rpt0 & 16u) != 0)) {
        gt_sfx(0, -1);
        lcl_flash = 8;
    }
    if (((gt_rpt0 & 4096u) != 0)) {
        gt_sfx(3, -1);
        lcl_flash = 8;
    }
    if (((gt_rpt0 & 8192u) != 0)) {
        gt_sfx(1, -1);
        lcl_flash = 8;
    }
    if (((gt_rpt0 & 1028u) != 0)) {
        gt_sfx(5, 2);
        lcl_flash = 8;
    }
    if (((gt_rpt0 & 2056u) != 0)) {
        if ((lcl_playing == 1)) {
            gt_music((-1), 1);
            lcl_playing = 0;
        } else {
            gt_music(0, 1);
            lcl_playing = 1;
        }
    }
    if ((lcl_flash > 0)) {
        lcl_flash = (lcl_flash - 1);
    }
}

static void lcl__draw(void)
{
    gt_cls(169);
    { int lcl_c = 8;
        if ((lcl_flash > 0)) {
            lcl_c = 10;
        }
        (gt_a0 = 64, gt_a1 = 60, gt_a2 = 20, gt_a3 = lcl_c, gt_circfill_z());
        gt_print("sfx + music", 34, 18, 7);
        if ((lcl_playing == 1)) {
            gt_print("music: on", 42, 100, 254);
        } else {
            gt_print("music: off", 40, 100, 91);
        }
    }
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    gt_audio_init();
    gt_music_init();
    lcl__init();
    for (;;) {
        gt_update_inputs();
        lcl__update60();
        lcl__draw();
        gt_endframe();
    }
}
