/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void gtl__draw(void);

static void gtl__draw(void)
{
    gt_p8_cls(169);
    gt_p8_print("hello gametank", 38, 14, 94);
    (gt_a0 = 64, gt_a1 = 72, gt_a2 = 26, gt_a3 = 31, gt_p8_circfill_z());
    (gt_a0 = 53, gt_a1 = 62, gt_a2 = 58, gt_a3 = 68, gt_a4 = 0, gt_p8_rectfill_z());
    (gt_a0 = 70, gt_a1 = 62, gt_a2 = 75, gt_a3 = 68, gt_a4 = 0, gt_p8_rectfill_z());
    (gt_a0 = 64, gt_a1 = 82, gt_a2 = 9, gt_a3 = 0, gt_p8_circfill_z());
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    for (;;) {
        gt_update_inputs();
        gtl__draw();
        gt_endframe();
    }
}
