/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void gtl__init(void);
static void gtl__update60(void);
static void gtl__draw(void);

int gtl_in3 = 3;
int gtl_in2 = 2;
int gtl_inm9 = -9;
long gtl_inm23 = -150733L; /* -2.3 */
long gtl_quarter = 16384L; /* 0.25 */
int gtl_in16 = 16;
int gtl_none = 1;
int gtl_ntwo = 1;
long gtl_r_div = 0L; /* 0 */
int gtl_r_flr = 0;
long gtl_r_sin = 0L; /* 0 */
int gtl_r_bslash = 0;
int gtl_r_mod = 0;
int gtl_r_mid = 0;
long gtl_r_sqrt = 0L; /* 0 */
long gtl_r_atan = 0L; /* 0 */
long gtl_r_cos = 0L; /* 0 */
long gtl_r_div0 = 0L; /* 0 */
int gtl_r_wrap = 0;

static void gtl__init(void)
{
    gtl_none = 1;
    gtl_ntwo = 0;
    gtl_r_div = (fa = ((long)gtl_in3 << 16), fb = ((long)gtl_in2 << 16), gt_fdiv_zp());
    gtl_r_flr = (int)(gtl_inm23 >> 16);
    gtl_r_sin = gt_fsin(gtl_quarter);
    gtl_r_bslash = gt_ifdiv(gtl_inm9, gtl_in2);
    gtl_r_mod = gt_ifmod(gtl_inm9, gtl_in2);
    gtl_r_mid = (((unsigned char)0 < (unsigned char)200) ? (((unsigned char)200 < (unsigned char)127) ? (200) : (((unsigned char)0 < (unsigned char)127) ? (127) : (0))) : (((unsigned char)0 < (unsigned char)127) ? (0) : (((unsigned char)200 < (unsigned char)127) ? (127) : (200))));
    gtl_r_sqrt = gt_fsqrt(((long)gtl_in16 << 16));
    gtl_r_atan = gt_fatan2(((long)gtl_none << 16), ((long)gtl_none << 16));
    gtl_r_cos = gt_fcos((gtl_quarter * gtl_in2));
    gtl_r_div0 = (fa = ((long)gtl_none << 16), fb = ((long)gtl_ntwo << 16), gt_fdiv_zp());
    gtl_r_wrap = (((((((gtl_in3) << 6) + ((gtl_in3) << 5) + ((gtl_in3) << 2)) * gtl_in3)) << 6) + ((((((gtl_in3) << 6) + ((gtl_in3) << 5) + ((gtl_in3) << 2)) * gtl_in3)) << 5) + ((((((gtl_in3) << 6) + ((gtl_in3) << 5) + ((gtl_in3) << 2)) * gtl_in3)) << 2));
}

static void gtl__update60(void)
{
}

static void gtl__draw(void)
{
    gt_p8_cls(219);
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    gtl__init();
    for (;;) {
        gt_update_inputs();
        gtl__update60();
        gtl__draw();
        gt_endframe();
    }
}
