/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__init(void);
static void lcl__update60(void);
static void lcl__draw(void);

int lcl_in3 = 3;
int lcl_in2 = 2;
int lcl_inm9 = -9;
long lcl_inm23 = -150733L; /* -2.3 */
long lcl_quarter = 16384L; /* 0.25 */
int lcl_in16 = 16;
int lcl_none = 1;
int lcl_ntwo = 1;
long lcl_r_div = 0L; /* 0 */
int lcl_r_flr = 0;
long lcl_r_sin = 0L; /* 0 */
int lcl_r_bslash = 0;
int lcl_r_mod = 0;
int lcl_r_mid = 0;
long lcl_r_sqrt = 0L; /* 0 */
long lcl_r_atan = 0L; /* 0 */
long lcl_r_cos = 0L; /* 0 */
long lcl_r_div0 = 0L; /* 0 */
int lcl_r_wrap = 0;

static void lcl__init(void)
{
    lcl_none = 1;
    lcl_ntwo = 0;
    lcl_r_div = (fa = ((long)lcl_in3 << 16), fb = ((long)lcl_in2 << 16), gt_fdiv_zp());
    lcl_r_flr = (int)(lcl_inm23 >> 16);
    lcl_r_sin = gt_fsin(lcl_quarter);
    lcl_r_bslash = gt_ifdiv(lcl_inm9, lcl_in2);
    lcl_r_mod = gt_ifmod(lcl_inm9, lcl_in2);
    lcl_r_mid = (((unsigned char)0 < (unsigned char)200) ? (((unsigned char)200 < (unsigned char)127) ? (200) : (((unsigned char)0 < (unsigned char)127) ? (127) : (0))) : (((unsigned char)0 < (unsigned char)127) ? (0) : (((unsigned char)200 < (unsigned char)127) ? (127) : (200))));
    lcl_r_sqrt = gt_fsqrt(((long)lcl_in16 << 16));
    lcl_r_atan = gt_fatan2(((long)lcl_none << 16), ((long)lcl_none << 16));
    lcl_r_cos = gt_fcos((lcl_quarter * lcl_in2));
    lcl_r_div0 = (fa = ((long)lcl_none << 16), fb = ((long)lcl_ntwo << 16), gt_fdiv_zp());
    lcl_r_wrap = (((((((lcl_in3) << 6) + ((lcl_in3) << 5) + ((lcl_in3) << 2)) * lcl_in3)) << 6) + ((((((lcl_in3) << 6) + ((lcl_in3) << 5) + ((lcl_in3) << 2)) * lcl_in3)) << 5) + ((((((lcl_in3) << 6) + ((lcl_in3) << 5) + ((lcl_in3) << 2)) * lcl_in3)) << 2));
}

static void lcl__update60(void)
{
}

static void lcl__draw(void)
{
    gt_cls(219);
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    lcl__init();
    for (;;) {
        gt_update_inputs();
        lcl__update60();
        lcl__draw();
        gt_endframe();
    }
}
