/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void gtl__init(void);
static void gtl_spawn_star(void);
static void gtl__update(void);
static void gtl__draw(void);

long gtl_sx = 4194304L; /* 64 */
long gtl_sy = 4194304L; /* 64 */
long gtl_vx = 0L; /* 0 */
long gtl_vy = 0L; /* 0 */
long gtl_facing = 0L; /* 0 */
int gtl_score = 0;
unsigned char gtl_col[4];
int gtl_star_cx[3];
int gtl_star_cy[3];
int gtl_star_r[3];
long gtl_star_ph[3];
long gtl_star_sp[3];

static void gtl__init(void)
{
    gtl_col[0] = 0xbd;
    gtl_col[1] = 0xfd;
    gtl_col[2] = 0x3f;
    gtl_col[3] = 0x5e;
    gt_p8_srand(196608L);
    { unsigned char gtl_i = 1; unsigned char L_lim0 = 3;
        for (; gtl_i <= L_lim0; ++gtl_i) {
            (gt_p0 = gtl_i, gtl_spawn_star());
        }
    }
}

static void gtl_spawn_star(void)
{
    gtl_star_cx[gt_p0 - 1] = (20 + gt_p8_rnd_int(88));
    gtl_star_cy[gt_p0 - 1] = (20 + gt_p8_rnd_int(88));
    gtl_star_r[gt_p0 - 1] = (10 + gt_p8_rnd_int(22));
    gtl_star_ph[gt_p0 - 1] = gt_p8_rnd(65536L);
    gtl_star_sp[gt_p0 - 1] = (262L /* 0.004 */ + gt_p8_rnd(655L /* 0.01 */));
}

static void gtl__update(void)
{
    { long gtl_tx = 0L;
        { long gtl_ty = 0L;
            if (((gt_pad0 & 512u) != 0)) {
                gtl_tx = (gtl_tx - 65536L);
            }
            if (((gt_pad0 & 256u) != 0)) {
                gtl_tx = (gtl_tx + 65536L);
            }
            if (((gt_pad0 & 2056u) != 0)) {
                gtl_ty = (gtl_ty - 65536L);
            }
            if (((gt_pad0 & 1028u) != 0)) {
                gtl_ty = (gtl_ty + 65536L);
            }
            if (((gtl_tx != 0L) || (gtl_ty != 0L))) {
                gtl_vx = (gtl_vx + (fa = gtl_tx, fb = 3932L /* 0.06 */, gt_fmul_zp()));
                gtl_vy = (gtl_vy + (fa = gtl_ty, fb = 3932L /* 0.06 */, gt_fmul_zp()));
                gtl_facing = gt_fatan2(gtl_tx, gtl_ty);
            }
            if (((gt_rpt0 & 16u) != 0)) {
                gtl_vx = (gtl_vx + gt_fmul(gt_fcos(gtl_facing), 98304L /* 1.5 */));
                gtl_vy = (gtl_vy + gt_fmul(gt_fsin(gtl_facing), 98304L /* 1.5 */));
                gt_sfx(4, -1);
            }
            if (((gt_rpt0 & 4096u) != 0)) {
                gt_sfx(7, -1);
            }
            gtl_vx = (gtl_vx - (fa = gtl_vx, fb = 1966L /* 0.03 */, gt_fmul_zp()));
            gtl_vy = (gtl_vy - (fa = gtl_vy, fb = 1966L /* 0.03 */, gt_fmul_zp()));
            gtl_sx = (gtl_sx + gtl_vx);
            gtl_sy = (gtl_sy + gtl_vy);
            if ((gtl_sx < 262144L)) {
                gtl_sx = 262144L;
                gtl_vx = (fa = (-gtl_vx), fb = 39322L /* 0.6 */, gt_fmul_zp());
                gt_sfx(6, -1);
            }
            if ((gtl_sx > 8060928L)) {
                gtl_sx = 8060928L;
                gtl_vx = (fa = (-gtl_vx), fb = 39322L /* 0.6 */, gt_fmul_zp());
                gt_sfx(6, -1);
            }
            if ((gtl_sy < 262144L)) {
                gtl_sy = 262144L;
                gtl_vy = (fa = (-gtl_vy), fb = 39322L /* 0.6 */, gt_fmul_zp());
                gt_sfx(6, -1);
            }
            if ((gtl_sy > 8060928L)) {
                gtl_sy = 8060928L;
                gtl_vy = (fa = (-gtl_vy), fb = 39322L /* 0.6 */, gt_fmul_zp());
                gt_sfx(6, -1);
            }
            { int gtl_shipx = (int)(gtl_sx >> 16);
                { int gtl_shipy = (int)(gtl_sy >> 16);
                    { unsigned char gtl_i = 1; unsigned char L_lim1 = 3;
                        for (; gtl_i <= L_lim1; ++gtl_i) {
                            gtl_star_ph[gtl_i - 1] = ((gtl_star_ph - 1)[gtl_i] + (gtl_star_sp - 1)[gtl_i]);
                            { int gtl_ex = ((gtl_star_cx - 1)[gtl_i] + (int)((gt_fcos((gtl_star_ph - 1)[gtl_i]) * (gtl_star_r - 1)[gtl_i]) >> 16));
                                { int gtl_ey = ((gtl_star_cy - 1)[gtl_i] + (int)((gt_fsin((gtl_star_ph - 1)[gtl_i]) * (gtl_star_r - 1)[gtl_i]) >> 16));
                                    { int gtl_dx = (gtl_ex - gtl_shipx);
                                        { int gtl_dy = (gtl_ey - gtl_shipy);
                                            if ((((((gtl_dx - ((-5))) > 0) && (gtl_dx < 5)) && ((gtl_dy - ((-5))) > 0)) && (gtl_dy < 5))) {
                                                gtl_score = (gtl_score + 1);
                                                gt_sfx(1, -1);
                                                (gt_p0 = gtl_i, gtl_spawn_star());
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

static void gtl__draw(void)
{
    gt_p8_cls(169);
    { int gtl_shipx = (int)(gtl_sx >> 16);
        { int gtl_shipy = (int)(gtl_sy >> 16);
            { unsigned char gtl_i = 1; unsigned char L_lim2 = 3;
                for (; gtl_i <= L_lim2; ++gtl_i) {
                    { int gtl_ex = ((gtl_star_cx - 1)[gtl_i] + (int)((gt_fcos((gtl_star_ph - 1)[gtl_i]) * (gtl_star_r - 1)[gtl_i]) >> 16));
                        { int gtl_ey = ((gtl_star_cy - 1)[gtl_i] + (int)((gt_fsin((gtl_star_ph - 1)[gtl_i]) * (gtl_star_r - 1)[gtl_i]) >> 16));
                            (gt_a0 = (gtl_star_cx - 1)[gtl_i], gt_a1 = (gtl_star_cy - 1)[gtl_i], gt_a2 = 3, gt_p8_pset_z());
                            (gt_a0 = gtl_ex, gt_a1 = gtl_ey, gt_a2 = 2, gt_a3 = 31, gt_p8_circfill_z());
                            (gt_a0 = gtl_ex, gt_a1 = (gtl_ey - 3), gt_a2 = 7, gt_p8_pset_z());
                        }
                    }
                }
            }
            { int gtl_c = gtl_col[(gtl_score & 3)];
                (gt_a0 = gtl_shipx, gt_a1 = gtl_shipy, gt_a2 = 4, gt_a3 = gtl_c, gt_p8_circfill_z());
                { int gtl_nx = (gtl_shipx + (int)((gt_fcos(gtl_facing) * 6) >> 16));
                    { int gtl_ny = (gtl_shipy + (int)((gt_fsin(gtl_facing) * 6) >> 16));
                        (gt_a0 = gtl_nx, gt_a1 = gtl_ny, gt_a2 = 7, gt_p8_pset_z());
                        gt_p8_print("score", 4, 4, 7);
                        gt_p8_print_int(gtl_score, 44, 4, 31);
                        gt_p8_print("d-pad fly  A boost", 4, 118, 6);
                    }
                }
            }
        }
    }
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    gt_audio_init();
    gt_music_init();
    gt_p8_fps30();
    gtl__init();
    for (;;) {
        gt_update_inputs();
        gtl__update();
        gtl__draw();
        gt_endframe();
    }
}
