/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__init(void);
static void lcl_spawn_star(void);
static void lcl__update(void);
static void lcl__draw(void);

long lcl_sx = 4194304L; /* 64 */
long lcl_sy = 4194304L; /* 64 */
long lcl_vx = 0L; /* 0 */
long lcl_vy = 0L; /* 0 */
long lcl_facing = 0L; /* 0 */
int lcl_score = 0;
unsigned char lcl_col[4];
int lcl_star_cx[3];
int lcl_star_cy[3];
int lcl_star_r[3];
long lcl_star_ph[3];
long lcl_star_sp[3];

static void lcl__init(void)
{
    lcl_col[0] = 0xbd;
    lcl_col[1] = 0xfd;
    lcl_col[2] = 0x3f;
    lcl_col[3] = 0x5e;
    gt_srand(196608L);
    { unsigned char lcl_i = 1; unsigned char L_lim0 = 3;
        for (; lcl_i <= L_lim0; ++lcl_i) {
            (gt_p0 = lcl_i, lcl_spawn_star());
        }
    }
}

static void lcl_spawn_star(void)
{
    lcl_star_cx[gt_p0 - 1] = (20 + gt_rnd_int(88));
    lcl_star_cy[gt_p0 - 1] = (20 + gt_rnd_int(88));
    lcl_star_r[gt_p0 - 1] = (10 + gt_rnd_int(22));
    lcl_star_ph[gt_p0 - 1] = gt_rnd(65536L);
    lcl_star_sp[gt_p0 - 1] = (262L /* 0.004 */ + gt_rnd(655L /* 0.01 */));
}

static void lcl__update(void)
{
    { long lcl_tx = 0L;
        { long lcl_ty = 0L;
            if (((gt_pad0 & 512u) != 0)) {
                lcl_tx = (lcl_tx - 65536L);
            }
            if (((gt_pad0 & 256u) != 0)) {
                lcl_tx = (lcl_tx + 65536L);
            }
            if (((gt_pad0 & 2056u) != 0)) {
                lcl_ty = (lcl_ty - 65536L);
            }
            if (((gt_pad0 & 1028u) != 0)) {
                lcl_ty = (lcl_ty + 65536L);
            }
            if (((lcl_tx != 0L) || (lcl_ty != 0L))) {
                lcl_vx = (lcl_vx + (fa = lcl_tx, fb = 3932L /* 0.06 */, gt_fmul_zp()));
                lcl_vy = (lcl_vy + (fa = lcl_ty, fb = 3932L /* 0.06 */, gt_fmul_zp()));
                lcl_facing = gt_fatan2(lcl_tx, lcl_ty);
            }
            if (((gt_rpt0 & 16u) != 0)) {
                lcl_vx = (lcl_vx + gt_fmul(gt_fcos(lcl_facing), 98304L /* 1.5 */));
                lcl_vy = (lcl_vy + gt_fmul(gt_fsin(lcl_facing), 98304L /* 1.5 */));
                gt_sfx(4, -1);
            }
            if (((gt_rpt0 & 4096u) != 0)) {
                gt_sfx(7, -1);
            }
            lcl_vx = (lcl_vx - (fa = lcl_vx, fb = 1966L /* 0.03 */, gt_fmul_zp()));
            lcl_vy = (lcl_vy - (fa = lcl_vy, fb = 1966L /* 0.03 */, gt_fmul_zp()));
            lcl_sx = (lcl_sx + lcl_vx);
            lcl_sy = (lcl_sy + lcl_vy);
            if ((lcl_sx < 262144L)) {
                lcl_sx = 262144L;
                lcl_vx = (fa = (-lcl_vx), fb = 39322L /* 0.6 */, gt_fmul_zp());
                gt_sfx(6, -1);
            }
            if ((lcl_sx > 8060928L)) {
                lcl_sx = 8060928L;
                lcl_vx = (fa = (-lcl_vx), fb = 39322L /* 0.6 */, gt_fmul_zp());
                gt_sfx(6, -1);
            }
            if ((lcl_sy < 262144L)) {
                lcl_sy = 262144L;
                lcl_vy = (fa = (-lcl_vy), fb = 39322L /* 0.6 */, gt_fmul_zp());
                gt_sfx(6, -1);
            }
            if ((lcl_sy > 8060928L)) {
                lcl_sy = 8060928L;
                lcl_vy = (fa = (-lcl_vy), fb = 39322L /* 0.6 */, gt_fmul_zp());
                gt_sfx(6, -1);
            }
            { int lcl_shipx = (int)(lcl_sx >> 16);
                { int lcl_shipy = (int)(lcl_sy >> 16);
                    { unsigned char lcl_i = 1; unsigned char L_lim1 = 3;
                        for (; lcl_i <= L_lim1; ++lcl_i) {
                            lcl_star_ph[lcl_i - 1] = ((lcl_star_ph - 1)[lcl_i] + (lcl_star_sp - 1)[lcl_i]);
                            { int lcl_ex = ((lcl_star_cx - 1)[lcl_i] + (int)((gt_fcos((lcl_star_ph - 1)[lcl_i]) * (lcl_star_r - 1)[lcl_i]) >> 16));
                                { int lcl_ey = ((lcl_star_cy - 1)[lcl_i] + (int)((gt_fsin((lcl_star_ph - 1)[lcl_i]) * (lcl_star_r - 1)[lcl_i]) >> 16));
                                    { int lcl_dx = (lcl_ex - lcl_shipx);
                                        { int lcl_dy = (lcl_ey - lcl_shipy);
                                            if ((((((lcl_dx - ((-5))) > 0) && (lcl_dx < 5)) && ((lcl_dy - ((-5))) > 0)) && (lcl_dy < 5))) {
                                                lcl_score = (lcl_score + 1);
                                                gt_sfx(1, -1);
                                                (gt_p0 = lcl_i, lcl_spawn_star());
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

static void lcl__draw(void)
{
    gt_cls(169);
    { int lcl_shipx = (int)(lcl_sx >> 16);
        { int lcl_shipy = (int)(lcl_sy >> 16);
            { unsigned char lcl_i = 1; unsigned char L_lim2 = 3;
                for (; lcl_i <= L_lim2; ++lcl_i) {
                    { int lcl_ex = ((lcl_star_cx - 1)[lcl_i] + (int)((gt_fcos((lcl_star_ph - 1)[lcl_i]) * (lcl_star_r - 1)[lcl_i]) >> 16));
                        { int lcl_ey = ((lcl_star_cy - 1)[lcl_i] + (int)((gt_fsin((lcl_star_ph - 1)[lcl_i]) * (lcl_star_r - 1)[lcl_i]) >> 16));
                            (gt_a0 = (lcl_star_cx - 1)[lcl_i], gt_a1 = (lcl_star_cy - 1)[lcl_i], gt_a2 = 3, gt_pset_z());
                            (gt_a0 = lcl_ex, gt_a1 = lcl_ey, gt_a2 = 2, gt_a3 = 31, gt_circfill_z());
                            (gt_a0 = lcl_ex, gt_a1 = (lcl_ey - 3), gt_a2 = 7, gt_pset_z());
                        }
                    }
                }
            }
            { int lcl_c = lcl_col[(lcl_score & 3)];
                (gt_a0 = lcl_shipx, gt_a1 = lcl_shipy, gt_a2 = 4, gt_a3 = lcl_c, gt_circfill_z());
                { int lcl_nx = (lcl_shipx + (int)((gt_fcos(lcl_facing) * 6) >> 16));
                    { int lcl_ny = (lcl_shipy + (int)((gt_fsin(lcl_facing) * 6) >> 16));
                        (gt_a0 = lcl_nx, gt_a1 = lcl_ny, gt_a2 = 7, gt_pset_z());
                        gt_print("score", 4, 4, 7);
                        gt_print_int(lcl_score, 44, 4, 31);
                        gt_print("d-pad fly  A boost", 4, 118, 6);
                    }
                }
            }
        }
    }
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    gt_audio_init();
    gt_music_init();
    gt_fps30();
    lcl__init();
    for (;;) {
        gt_update_inputs();
        lcl__update();
        lcl__draw();
        gt_endframe();
    }
}
