/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__init(void);
static void lcl__update60(void);
static void lcl__draw(void);

int lcl_x = 60;
int lcl_y = 60;
int lcl_size = 8;
unsigned char lcl_pal[6];
int lcl_ci = 0;
int lcl_speed = 2;

static void lcl__init(void)
{
    lcl_pal[0] = 0x5b;
    lcl_pal[1] = 0x3e;
    lcl_pal[2] = 0x3f;
    lcl_pal[3] = 0xfd;
    lcl_pal[4] = 0xbd;
    lcl_pal[5] = 0x5e;
}

static void lcl__update60(void)
{
    if (((gt_pad0 & 512u) != 0)) {
        lcl_x = (lcl_x - lcl_speed);
    }
    if (((gt_pad0 & 256u) != 0)) {
        lcl_x = (lcl_x + lcl_speed);
    }
    if (((gt_pad0 & 2056u) != 0)) {
        lcl_y = (lcl_y - lcl_speed);
    }
    if (((gt_pad0 & 1028u) != 0)) {
        lcl_y = (lcl_y + lcl_speed);
    }
    if (((gt_rpt0 & 16u) != 0)) {
        lcl_ci = gt_ifmod((lcl_ci + 1), 6);
    }
    if (((gt_rpt0 & 4096u) != 0)) {
        lcl_size = ((4 < (lcl_size + 4)) ? (((lcl_size + 4) < 32) ? ((lcl_size + 4)) : (((unsigned char)4 < (unsigned char)32) ? (32) : (4))) : (((unsigned char)4 < (unsigned char)32) ? (4) : (((lcl_size + 4) < 32) ? (32) : ((lcl_size + 4)))));
    }
    if (((gt_rpt0 & 8192u) != 0)) {
        lcl_size = ((4 < (lcl_size - 4)) ? (((lcl_size - 4) < 32) ? ((lcl_size - 4)) : (((unsigned char)4 < (unsigned char)32) ? (32) : (4))) : (((unsigned char)4 < (unsigned char)32) ? (4) : (((lcl_size - 4) < 32) ? (32) : ((lcl_size - 4)))));
    }
    lcl_x = ((0 < lcl_x) ? (((lcl_x - ((127 - lcl_size))) < 0) ? (lcl_x) : ((0 < (127 - lcl_size)) ? ((127 - lcl_size)) : (0))) : ((0 < (127 - lcl_size)) ? (0) : (((lcl_x - ((127 - lcl_size))) < 0) ? ((127 - lcl_size)) : (lcl_x))));
    lcl_y = ((0 < lcl_y) ? (((lcl_y - ((127 - lcl_size))) < 0) ? (lcl_y) : ((0 < (127 - lcl_size)) ? ((127 - lcl_size)) : (0))) : ((0 < (127 - lcl_size)) ? (0) : (((lcl_y - ((127 - lcl_size))) < 0) ? ((127 - lcl_size)) : (lcl_y))));
}

static void lcl__draw(void)
{
    gt_cls(169);
    (gt_a0 = lcl_x, gt_a1 = lcl_y, gt_a2 = ((lcl_x + lcl_size) - 1), gt_a3 = ((lcl_y + lcl_size) - 1), gt_a4 = lcl_pal[lcl_ci], gt_rectfill_z());
    (gt_a0 = (lcl_x - 2), gt_a1 = (lcl_y - 2), gt_a2 = ((lcl_x + lcl_size) + 1), gt_a3 = ((lcl_y + lcl_size) + 1), gt_a4 = 7, gt_rect_z());
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    lcl__init();
    for (;;) {
        gt_update_inputs();
        lcl__update60();
        lcl__draw();
        gt_endframe();
    }
}
