/* generated by gtlua from main.lua - edit the .lua, not this file */
#include "gt_api.h"

static void gtl__init(void);
static void gtl__update60(void);
static void gtl__draw(void);

int gtl_x = 60;
int gtl_y = 60;
int gtl_size = 8;
unsigned char gtl_pal[6];
int gtl_ci = 0;
int gtl_speed = 2;

static void gtl__init(void)
{
    gtl_pal[0] = 0x5b;
    gtl_pal[1] = 0x3e;
    gtl_pal[2] = 0x3f;
    gtl_pal[3] = 0xfd;
    gtl_pal[4] = 0xbd;
    gtl_pal[5] = 0x5e;
}

static void gtl__update60(void)
{
    if (((gt_pad0 & 512u) != 0)) {
        gtl_x = (gtl_x - gtl_speed);
    }
    if (((gt_pad0 & 256u) != 0)) {
        gtl_x = (gtl_x + gtl_speed);
    }
    if (((gt_pad0 & 2056u) != 0)) {
        gtl_y = (gtl_y - gtl_speed);
    }
    if (((gt_pad0 & 1028u) != 0)) {
        gtl_y = (gtl_y + gtl_speed);
    }
    if (((gt_rpt0 & 16u) != 0)) {
        gtl_ci = gt_ifmod((gtl_ci + 1), 6);
    }
    if (((gt_rpt0 & 4096u) != 0)) {
        gtl_size = ((4 < (gtl_size + 4)) ? (((gtl_size + 4) < 32) ? ((gtl_size + 4)) : (((unsigned char)4 < (unsigned char)32) ? (32) : (4))) : (((unsigned char)4 < (unsigned char)32) ? (4) : (((gtl_size + 4) < 32) ? (32) : ((gtl_size + 4)))));
    }
    if (((gt_rpt0 & 8192u) != 0)) {
        gtl_size = ((4 < (gtl_size - 4)) ? (((gtl_size - 4) < 32) ? ((gtl_size - 4)) : (((unsigned char)4 < (unsigned char)32) ? (32) : (4))) : (((unsigned char)4 < (unsigned char)32) ? (4) : (((gtl_size - 4) < 32) ? (32) : ((gtl_size - 4)))));
    }
    gtl_x = ((0 < gtl_x) ? (((gtl_x - ((127 - gtl_size))) < 0) ? (gtl_x) : ((0 < (127 - gtl_size)) ? ((127 - gtl_size)) : (0))) : ((0 < (127 - gtl_size)) ? (0) : (((gtl_x - ((127 - gtl_size))) < 0) ? ((127 - gtl_size)) : (gtl_x))));
    gtl_y = ((0 < gtl_y) ? (((gtl_y - ((127 - gtl_size))) < 0) ? (gtl_y) : ((0 < (127 - gtl_size)) ? ((127 - gtl_size)) : (0))) : ((0 < (127 - gtl_size)) ? (0) : (((gtl_y - ((127 - gtl_size))) < 0) ? ((127 - gtl_size)) : (gtl_y))));
}

static void gtl__draw(void)
{
    gt_p8_cls(169);
    (gt_a0 = gtl_x, gt_a1 = gtl_y, gt_a2 = ((gtl_x + gtl_size) - 1), gt_a3 = ((gtl_y + gtl_size) - 1), gt_a4 = gtl_pal[gtl_ci], gt_p8_rectfill_z());
    (gt_a0 = (gtl_x - 2), gt_a1 = (gtl_y - 2), gt_a2 = ((gtl_x + gtl_size) + 1), gt_a3 = ((gtl_y + gtl_size) + 1), gt_a4 = 7, gt_p8_rect_z());
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    gtl__init();
    for (;;) {
        gt_update_inputs();
        gtl__update60();
        gtl__draw();
        gt_endframe();
    }
}
