/* generated by gtlua from synth-btn.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__update(void);
static void lcl__draw(void);

static void lcl__update(void)
{
    if (((gt_pad0 & 512u) != 0)) {
    }
    if (((gt_rpt0 & 16u) != 0)) {
    }
}

static void lcl__draw(void)
{
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    gt_fps30();
    for (;;) {
        gt_update_inputs();
        lcl__update();
        lcl__draw();
        gt_endframe();
    }
}
