/* generated by gtlua from synth-shapes.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__draw(void);

static void lcl__draw(void)
{
    gt_cls(169);
    (gt_a0 = 4, gt_a1 = 4, gt_a2 = 20, gt_a3 = 20, gt_a4 = 91, gt_rectfill_z());
    (gt_a0 = 64, gt_a1 = 64, gt_a2 = 10, gt_a3 = 31, gt_circfill_z());
    (gt_a0 = 0, gt_a1 = 0, gt_a2 = 127, gt_a3 = 127, gt_a4 = 7, gt_line_z());
    (gt_a0 = 0, gt_a1 = 10, gt_a2 = 10, gt_a3 = 1, gt_a4 = 1, gt_a5 = 0 | (0 << 1), gt_spr_z());
    gt_print("hi", 4, 4, 7);
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    for (;;) {
        gt_update_inputs();
        lcl__draw();
        gt_endframe();
    }
}
