/* generated by gtlua from synth-btn.lua - edit the .lua, not this file */
#include "gt_api.h"

static void gtl__update(void);
static void gtl__draw(void);

static void gtl__update(void)
{
    if (((gt_pad0 & 512u) != 0)) {
    }
    if (((gt_rpt0 & 16u) != 0)) {
    }
}

static void gtl__draw(void)
{
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    gt_p8_fps30();
    for (;;) {
        gt_update_inputs();
        gtl__update();
        gtl__draw();
        gt_endframe();
    }
}
