/* generated by gtlua from synth-fixedmath-num8.lua - edit the .lua, not this file */
#include "gt_api.h"

static void gtl__update(void);
static void gtl__draw(void);

int gtl_x = 0; /* 0 */

static void gtl__update(void)
{
    gtl_x = (gtl_x + 128 /* 0.5 */);
    gtl_x = ((gtl_x) + ((gtl_x) >> 1));
    gtl_x = (fa = gtl_x, fb = 768, gt_fdiv_zp());
}

static void gtl__draw(void)
{
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    gt_p8_fps30();
    for (;;) {
        gt_update_inputs();
        gtl__update();
        gtl__draw();
        gt_endframe();
    }
}
