/* generated by gtlua from synth-fixedmath-num8.lua - edit the .lua, not this file */
#include "gt_api.h"

static void lcl__update(void);
static void lcl__draw(void);

int lcl_x = 0; /* 0 */

static void lcl__update(void)
{
    lcl_x = (lcl_x + 128 /* 0.5 */);
    lcl_x = ((lcl_x) + ((lcl_x) >> 1));
    lcl_x = (fa = lcl_x, fb = 768, gt_fdiv_zp());
}

static void lcl__draw(void)
{
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    gt_fps30();
    for (;;) {
        gt_update_inputs();
        lcl__update();
        lcl__draw();
        gt_endframe();
    }
}
