/* generated by gtlua from synth-func.lua - edit the .lua, not this file */
#include "gt_api.h"

static int lcl_helper(void);
static void lcl__update(void);
static void lcl__draw(void);

static int lcl_helper(void)
{
    return (gt_p0 + gt_p1);
}

static void lcl__update(void)
{
    { int lcl_z = (((1) + (2)));
    }
}

static void lcl__draw(void)
{
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    gt_fps30();
    for (;;) {
        gt_update_inputs();
        lcl__update();
        lcl__draw();
        gt_endframe();
    }
}
