/* generated by gtlua from synth-array.lua - edit the .lua, not this file */
#include "gt_api.h"

static void gtl__update(void);
static void gtl__draw(void);

int gtl_a[16];
unsigned char gtl_b[8];

static void gtl__update(void)
{
    gtl_a[0] = 5;
    gtl_b[0] = 2;
}

static void gtl__draw(void)
{
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    gt_p8_fps30();
    for (;;) {
        gt_update_inputs();
        gtl__update();
        gtl__draw();
        gt_endframe();
    }
}
