/* generated by gtlua from synth-minmax.lua - edit the .lua, not this file */
#include "gt_api.h"

static void gtl__update(void);
static void gtl__draw(void);

static void gtl__update(void)
{
    { int gtl_a = (((unsigned char)1 < (unsigned char)2) ? (1) : (2));
        { int gtl_b = (((unsigned char)3 > (unsigned char)4) ? (3) : (4));
            { int gtl_c = (((unsigned char)1 < (unsigned char)2) ? (((unsigned char)2 < (unsigned char)3) ? (2) : (((unsigned char)1 < (unsigned char)3) ? (3) : (1))) : (((unsigned char)1 < (unsigned char)3) ? (1) : (((unsigned char)2 < (unsigned char)3) ? (3) : (2))));
                { int gtl_d = gt_absi((-5));
                }
            }
        }
    }
}

static void gtl__draw(void)
{
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    gt_p8_fps30();
    for (;;) {
        gt_update_inputs();
        gtl__update();
        gtl__draw();
        gt_endframe();
    }
}
