/* generated by gtlua from synth-func.lua - edit the .lua, not this file */
#include "gt_api.h"

static int gtl_helper(void);
static void gtl__update(void);
static void gtl__draw(void);

static int gtl_helper(void)
{
    return (gt_p0 + gt_p1);
}

static void gtl__update(void)
{
    { int gtl_z = (((1) + (2)));
    }
}

static void gtl__draw(void)
{
}

void main(void)
{
    gt_init();
    gt_sheet_init();
    gt_p8_fps30();
    for (;;) {
        gt_update_inputs();
        gtl__update();
        gtl__draw();
        gt_endframe();
    }
}
